#!/bin/sh

HOST=localhost
PORT=4321

FILE1=/tmp/main1
FILE2=/tmp/main2
ERROR=/tmp/main-err

GETTEXT="gettext -d main_gui_network"


help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ "$1" = "--help" ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
elif [ $# -ge 3 ]
then
	help
	exit -1
fi
